git:
  depth: false
  
language: node_js
node_js:
  - "14"
  
branches:
  only:
    - master

before_deploy:
  - export TRAVIS_TAG=v`cat build/APP_VERSION`

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: build/gh-pages/index.html
    skip_cleanup: true
    on:
      branch: master

  - provider: pages
    local_dir: build/gh-pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master

env:
  global:
    secure: e+ueMNEIEHW/TU8jbRtPjsEf6wog/S0WCOZPd2p5Z4uTEpmkgKYJRvARP4UsQeIhRv9ZGq1Yl2IUfENPJUBnA39ZJUuZ+3ApypnEaW0zNzpv23zR360oK4WaH8nxWunCR5wgve/ZbCIAeFjJFqCTDTwVCBlRuwS2w0R5aQerhlAETtm15RkOTPCQ1psVtHEQecz7rSmEp+HzDj6JKiYFtrNgzdPRVGrVCfSrbakMddseL5iqFhOEejgtiq6ePeTKI97FWseTDpK6TtD37c/9LFpAwbulm2ln2ycpjo+duSxwzU7Okt7cUyYnPZ4flzzlCpSxVlwM39gtxScxrlIJr+sV2YYvrJmLoaZBRsPYvHYRlyOxow1POEcj4nsb/fH+Pf0xhxj9Vlmr1x3Dsor7OeEGCNDNiMBTNOgF9VaWcrvmGO8iNotAmh5iXjE9OzU/KP5I/jssSb+kXTGydgvsCSHx2aKnLsGTY3zwq1zGdAePWoEUjqBJ+0xlBtTEPf74ihu++gQrIYFuwgDU6cgwVFVT4U+NiaHBh5s1KhbA36d40mKFvynqTYP+EwFLdc72QCDa6jJT53lYL0u132czgSR2qEZQXTFJBLfWY/pexLzLcnrUbJ3LI2XLCfKKnpyyBdCyugdwHwWGfvcFbt0xmA0w/h9at1ZBVqLHXw8fpbU=
